# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy all source files
COPY . .

# Install dependencies, build, and prune dev dependencies
RUN npm install --ignore-scripts && npm run build && chmod +x build/index.js && npm prune --production

# Default command
CMD ["node", "build/index.js"]
